version: '3.1'

services:
  database:
    image: healthcheck/mysql
#    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd!
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ava
    ports:
    - "3307:3306"
  ava_task:
    restart: always
    build: ./
    ports:
    - "8081:8080"
    depends_on:
    - database
